name: archaepaperswithcode
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Run archaepaperswithcode manually'
jobs:
  archaepaperswithcode-post:
    runs-on: ubuntu-latest
    env:
      TWITTER_CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
      TWITTER_CONSUMER_API_SECRET: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: Install libgit2
        run: sudo apt-get install -y libgit2-dev
      - name: Install R packages
        run: Rscript -e 'install.packages(c("git2r", "glue", "rtweet", "tidyverse"), repos = "https://cloud.r-project.org", dependencies = TRUE)'
      - name: Create and post tweet
        run: Rscript archaepaperswithcode.R
      - name: Keepalive Workflow
        uses: gautamkrishnar/keepalive-workflow@1.0.7


