name: archaepapersoncode
on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Run archaepapersoncode manually'
jobs:
  archaepaperswithcode-post:
    runs-on: ubuntu-latest
    env:
      TWITTER_CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
      TWITTER_CONSUMER_API_SECRET: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
      - name: Install ROpenSci/bibtex
        run: pak::pkg_install("ROpenSci/bibtex")
        shell: Rscript {0}
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 1
          packages: |
            any::tidyverse
            any::RefManageR
            any::rtweet
      - name: Create and post tweet
        run: Rscript archaepapersoncode.R
